<a href="https://colab.research.google.com/github/archita912/CODSOFT/blob/main/Creditcard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Loading the dataset

In [ ]:
creditcard_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
creditcard_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
creditcard_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7968,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
7969,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
7970,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
7971,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
7972,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset inormation
creditcard_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB

In [ ]:
# Cheching the no. of missing values in each column
creditcard_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions and fraudlent transaction
creditcard_data['Class'].value_counts()

0.0    7947
1.0      25
Name: Class, dtype: int64

The Dataset is highly unbalanced
0 -> Normal Transaction
1 -> Fraudlent transaction

In [ ]:
# Seperating the data for analysis
legit = creditcard_data[creditcard_data.Class == 0]
fraud = creditcard_data[creditcard_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(7947, 31)
(25, 31)

In [ ]:

# Statistical measure of the data
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# Compare the values for both transactions
creditcard_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Under Sampling

Build a sample dataset containing similar distribution of normal transaction and Fraudulent transaction

Number of Fraudulant Transaction --> 492

In [ ]:
legit_sample = legit.sample(n = 492)

Concatenation two DataFrames

In [ ]:
new_creditdataset = pd.concat([legit_sample, fraud], axis = 0)

In [ ]:
new_creditdataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5556,5667,1.096636,-0.528745,0.663772,0.129510,-0.946995,-0.199307,-0.654925,0.249677,2.218162,...,-0.401555,-1.016670,0.174682,0.154986,-0.149915,1.190446,-0.139664,-0.018703,45.00,0.0
6675,8265,-2.311510,-1.111537,2.270359,-2.169263,-0.427880,-1.361634,-0.223411,0.100169,3.125385,...,-0.010099,0.573552,0.581714,0.327708,0.677345,0.008967,0.488307,0.165438,106.67,0.0
3259,2809,-0.438813,0.681387,1.297765,-1.959230,0.102820,-1.338274,1.110342,-0.341033,0.787064,...,0.123546,0.770563,-0.201211,0.613286,-0.069293,-0.842888,0.256322,-0.011605,1.00,0.0
5589,5748,-0.811331,1.056297,0.848639,-1.262614,-0.057527,-0.444583,0.370695,0.145129,1.642523,...,-0.365665,-0.651932,-0.088407,-0.650460,-0.094648,0.725938,-0.022377,-0.183820,38.44,0.0
2606,2132,-1.348876,-0.104714,0.896352,0.086679,-0.455948,1.232446,-0.478116,0.747792,-1.327312,...,-0.126747,0.204169,-0.323231,-1.125836,-0.076791,-0.099103,0.327303,-0.023556,123.50,0.0

In [ ]:
new_creditdataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6870,8757,-1.863756,3.442644,-4.468260,2.805336,-2.118412,-2.332285,-4.261237,1.701682,-1.439396,...,0.667927,-0.516242,-0.012218,0.070614,0.058504,0.304883,0.418012,0.208858,1.00,1.0
6882,8808,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10,1.0
6899,8878,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1.0
6903,8886,-2.535852,5.793644,-7.618463,6.395830,-0.065210,-3.136372,-3.104557,1.823233,-3.878658,...,0.716720,-0.448060,-0.402407,-0.288835,1.011752,0.425965,0.413140,0.308205,1.00,1.0
6971,9064,-3.499108,0.258555,-4.489558,4.853894,-6.974522,3.628382,5.431271,-1.946734,-0.775680,...,-1.052368,0.204817,-2.119007,0.170279,-0.393844,0.296367,1.985913,-0.900452,1809.68,1.0

In [ ]:
new_creditdataset['Class'].value_counts()

0.0    492
1.0     25
Name: Class, dtype: int64

In [ ]:
new_creditdataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.78252,-0.376218,0.23977,0.898389,0.152338,-0.072323,0.166747,-0.034113,-0.106332,0.748729,...,0.027564,0.021135,-0.177831,-0.006203,0.032685,0.089230,0.021423,0.018627,-0.001985,74.837724
1.0,7359.24000,-1.154048,2.93088,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Splitting the data into Features and Targets

In [ ]:
X = new_creditdataset.drop(columns = 'Class',axis = 1)
Y = new_creditdataset['Class']

In [ ]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
5556  5667  1.096636 -0.528745  0.663772  0.129510 -0.946995 -0.199307
6675  8265 -2.311510 -1.111537  2.270359 -2.169263 -0.427880 -1.361634
3259  2809 -0.438813  0.681387  1.297765 -1.959230  0.102820 -1.338274
5589  5748 -0.811331  1.056297  0.848639 -1.262614 -0.057527 -0.444583
2606  2132 -1.348876 -0.104714  0.896352  0.086679 -0.455948  1.232446
...    ...       ...       ...       ...       ...       ...       ...
6870  8757 -1.863756  3.442644 -4.468260  2.805336 -2.118412 -2.332285
6882  8808 -4.617217  1.695694 -3.114372  4.328199 -1.873257 -0.989908
6899  8878 -2.661802  5.856393 -7.653616  6.379742 -0.060712 -3.131550
6903  8886 -2.535852  5.793644 -7.618463  6.395830 -0.065210 -3.136372
6971  9064 -3.499108  0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8        V9  ...       V20       V21       V22  \
5556 -0.654925  0.249677  2.218162  ... -0.292024 -0.401555 -1.016670
6675 -0.223411  0.100169  3.125385  ...  0.002609 -0.010099  0.573552
3259  1.110342 -0.341033  0.787064  ... -0.016228  0.123546  0.770563
5589  0.370695  0.145129  1.642523  ...  0.088174 -0.365665 -0.651932
2606 -0.478116  0.747792 -1.327312  ... -0.315705 -0.126747  0.204169
...        ...       ...       ...  ...       ...       ...       ...
6870 -4.261237  1.701682 -1.439396  ...  0.360924  0.667927 -0.516242
6882 -4.577265  0.472216  0.472017  ... -0.039046  0.481830  0.146023
6899 -3.103570  1.778492 -3.831154  ...  0.399097  0.734775 -0.435901
6903 -3.104557  1.823233 -3.878658  ...  0.408704  0.716720 -0.448060
6971  5.431271 -1.946734 -0.775680  ... -3.042626 -1.052368  0.204817

           V23       V24       V25       V26       V27       V28   Amount
5556  0.174682  0.154986 -0.149915  1.190446 -0.139664 -0.018703    45.00
6675  0.581714  0.327708  0.677345  0.008967  0.488307  0.165438   106.67
3259 -0.201211  0.613286 -0.069293 -0.842888  0.256322 -0.011605     1.00
5589 -0.088407 -0.650460 -0.094648  0.725938 -0.022377 -0.183820    38.44
2606 -0.323231 -1.125836 -0.076791 -0.099103  0.327303 -0.023556   123.50
...        ...       ...       ...       ...       ...       ...      ...
6870 -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
6882  0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
6899 -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
6903 -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
6971 -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[517 rows x 30 columns]

In [ ]:
print(Y)

5556    0.0
6675    0.0
3259    0.0
5589    0.0
2606    0.0
       ...
6870    1.0
6882    1.0
6899    1.0
6903    1.0
6971    1.0
Name: Class, Length: 517, dtype: float64

Split the data into Training data and Testing data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(517, 30) (413, 30) (104, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data :', training_data_accuracy)

Accuracy on Training data : 1.0

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test data :', test_data_accuracy)

Accuracy score on Test data : 0.9807692307692307